name: Feature Request
description: Suggest a new feature
type: "feature"
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature!
  - type: textarea
    id: feature
    attributes:
      label: Feature Description
      description: What feature would you like to see added?
      placeholder: Describe the feature and its use case
    validations:
      required: true
  - type: checkboxes
    id: maplibre_support
    attributes:
      label: MapLibre Support
      description: Which MapLibre SDKs support this feature
      options:
        - MapLibre Native for Android
        - MapLibre Native for iOS
        - MapLibre GL JS
  - type: textarea
    id: maplibre_docs
    attributes:
      label: MapLibre Documentation Links
      description: Please provide links to relevant MapLibre documentation
      placeholder: |
        - Android: https://maplibre.org/maplibre-native/android/api/...
        - iOS: https://maplibre.org/maplibre-native/ios/latest/documentation/maplibre/...
        - JS: https://maplibre.org/maplibre-gl-js/docs/...
  - type: dropdown
    id: willing_to_pr
    attributes:
      label: Implementation
      description: Would you be willing to implement this feature and submit a PR?
      options:
        - "Yes"
        - "No"
  - type: checkboxes
    id: development_platforms
    attributes:
      label: Development Platforms
      description: If you're willing to implement this, which platforms can you develop for?
      options:
        - Android
        - iOS
        - Browser
        - Linux (x86_64)
        - Linux (aarch64)
        - macOS (x86_64)
        - macOS (aarch64)
        - Windows (x86_64)
        - Windows (aarch64)
