---
name: "Label Actions"

on:
  pull_request:
    types: [labeled]

jobs:
  pr-format:
    runs-on: "ubuntu-latest"
    if: "github.event.label.name == 'action-pr-format'"
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: "actions/checkout@v4"
        with:
          ref: "${{ github.head_ref }}"
      - uses: "./.github/actions/setup"
      - run: "./gradlew spotlessApply"
      - uses: "stefanzweifel/git-auto-commit-action@v4"
        with:
          commit_message: "Apply formatting"
      - uses: "actions-ecosystem/action-remove-labels@v1"
        with:
          labels: "action-pr-format"
