---
name: "Label Actions"

on:
  pull_request_target:
    types: [labeled]

permissions:
  actions: write
  pull-requests: write

jobs:
  pr-format:
    runs-on: "ubuntu-latest"
    if: "github.event.label.name == 'action-pr-format'"
    steps:
      - uses: "benc-uk/workflow-dispatch@v1"
        with:
          workflow: "pr-format.yml"
          inputs: '{ "head_ref": "${{ github.event.pull_request.head.ref }}" }'
      - uses: "actions-ecosystem/action-remove-labels@v1"
        with:
          labels: "action-pr-format"
