---
name: "PR Format"

on:
  workflow_dispatch:
    inputs:
      head_ref:
        description: "The branch to run the CI job on"
        required: true

permissions:
  contents: write

jobs:
  pr-format:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
        with:
          ref: "${{ github.event.inputs.head_ref }}"
          token: "${{ secrets.ELEVATED_GITHUB_TOKEN }}"
      - uses: "./.github/actions/setup"
      - run: "./gradlew spotlessApply"
      - uses: "stefanzweifel/git-auto-commit-action@v4"
        with:
          commit_message: "Apply formatting"
          commit_options: "--no-verify"
          branch: "${{ github.event.inputs.head_ref }}"
          skip_fetch: true
          skip_checkout: true
